name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation
        run: yarn install --frozen-lockfile --non-interactive
        env:
          CI: true

      # TODO: ENABLE
      # # TODO(CI): Set up caching to speed up test specs
      # # Detect if `test/packages/*/*/node_modules` exists in any form and skip
      # # installs on a per-directory basis.
      # - name: Installation
      #   run: yarn benchmark:install --skip-if-exists
      #   env:
      #     CI: true

      - name: Checks (lint, unit tests)
        run: yarn run check

      # TODO: ENABLE
      # - name: CLI tests
      #   run: yarn run check

      # - name: Benchmark
      #   run: yarn benchmark --parallel
      # - name: Benchmark tests
      #   run: yarn benchmark:test
